language: node_js
dist: trusty
sudo: required
node_js: 6
env:
  - PATH=$HOME/purescript:$PATH
install:
  - wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/v0.11.3/linux64.tar.gz
  - tar -xvf $HOME/purescript.tar.gz -C $HOME/
  - chmod a+x $HOME/purescript
  - npm install -g bower pulp
script:
  - npm install && bower install && npm run compile
